1. Write a python program to print the matrix of 4 x 4 using List.

In [4]:
matrix = [[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
          [13, 14, 15, 16]]

for row in matrix:
    print(row)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


 3. Write a python & create a class named Employee with attributes name, position, and salary. Write a method to calculate the annual salary of the employee.


In [5]:
class Employee:
    def __init__(self, name, position, salary):
        self.name = name
        self.position = position
        self.salary = salary

    def calculate_annual_salary(self):
        return self.salary * 12

# Example usage:
employee = Employee("John Doe", "Manager", 50000)
annual_salary = employee.calculate_annual_salary()
print(f"{employee.name} earns ${annual_salary} annually as a {employee.position}.")


John Doe earns $600000 annually as a Manager.


4. Write a program that reads a CSV file and extracts specific columns from it, also handles a file-not- found error and prints a custom error message.

In [6]:
import csv

file_path = 'data.csv'  # Replace 'data.csv' with your CSV file path
columns_to_extract = [0, 2]  # Replace with the indices of the columns you want to extract (0-based)

try:
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        
        # Create a list to store the extracted columns
        extracted_columns = []

        for row in reader:
            # Check if the row has enough columns to extract
            if all(col_index < len(row) for col_index in columns_to_extract):
                selected_data = [row[col_index] for col_index in columns_to_extract]
                extracted_columns.append(selected_data)
            else:
                print(f"Skipping row with not enough columns: {row}")

        # Print the extracted columns
        for data in extracted_columns:
            print(data)
except FileNotFoundError:
    print(f"Error: File '{file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")


Error: File 'data.csv' not found.


9. Write a Python Program to Multiply Two Matrices and check resultant matrix order.

In [7]:
import numpy as np

# Define two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Check if the number of columns in A is equal to the number of rows in B for matrix multiplication
if A.shape[1] != B.shape[0]:
    print("Matrix multiplication not possible due to incompatible dimensions.")
else:
    # Multiply the matrices
    result = np.dot(A, B)

    # Get the shape (order) of the resultant matrix
    order = result.shape

    print("Matrix A:")
    print(A)
    print("\nMatrix B:")
    print(B)
    print("\nResultant Matrix:")
    print(result)
    print("\nOrder of Resultant Matrix:", order)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Resultant Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Order of Resultant Matrix: (3, 3)


2. Find the python program to find the odd numbers in the list of numbers entered by user.

In [3]:
# Input: Get a list of numbers from the user
num_list = input("Enter a list of numbers separated by spaces: ").split()

# Convert the input to a list of integers
num_list = [int(num) for num in num_list]

# Initialize an empty list to store odd numbers
odd_numbers = []

# Iterate through the list and check for odd numbers
for num in num_list:
    if num % 2 != 0:
        odd_numbers.append(num)

# Print the odd numbers
if odd_numbers:
    print("Odd numbers in the list:", odd_numbers)
else:
    print("No odd numbers found in the list.")

Odd numbers in the list: [1]
