In [6]:
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.datasets import mnist

# Load a dataset (e.g., MNIST)
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalize and preprocess the data
X_train = X_train / 255.0
X_test = X_test / 255.0

# Build a simple CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=64)

# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
accuracy = accuracy_score(y_test, y_pred_classes)
confusion = confusion_matrix(y_test, y_pred_classes)
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(confusion)


Epoch 1/5
938/938 [==============================] - 30s 29ms/step - loss: 0.1718 - accuracy: 0.9510
Epoch 2/5
938/938 [==============================] - 27s 29ms/step - loss: 0.0569 - accuracy: 0.9831
Epoch 3/5
938/938 [==============================] - 26s 27ms/step - loss: 0.0375 - accuracy: 0.9883
Epoch 4/5
938/938 [==============================] - 26s 28ms/step - loss: 0.0260 - accuracy: 0.9916
Epoch 5/5
313/313 [==============================] - 2s 5ms/step
Accuracy: 98.54%
Confusion Matrix:
[[ 974    0    1    0    0    1    2    1    0    1]
 [   0 1132    2    0    0    0    1    0    0    0]
 [   2    2 1014    0    3    0    0    4    6    1]
 [   0    0    4  993    0    7    0    3    2    1]
 [   0    0    0    0  975    0    1    0    1    5]
 [   2    0    1    7    0  873    7    0    1    1]
 [   8    2    1    0    7    1  939    0    0    0]
 [   0    2    6    1    0    0    0 1018    0    1]
 [   7    0    2    1    1    0    0    2  955    6]
 [   1    2    0   